name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          repository: doegox/rfidpics-engine
          persist-credentials: false
          path: build # need to be in a subdir

      - name: Checkout albums ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
          path: build/web/albums

      - name: Install and Build ğŸ”§
        run: |
          python2 -m pip install Pillow html
          # Restore existing cache files, if any
          ( cd build/web/albums;
            if git branch -a|grep -q remotes/origin/gh-pages; then
                /usr/bin/git restore --source origin/gh-pages cache;
                mv cache .. ;
            else
                mkdir -p ../cache;
            fi;
          )
          # Minify CSS & JS
          ( cd build/web; make; )
          # Scan pictures
          ( cd build/scanner; python2 main.py ../web/albums ../web/cache/; )
          # Prevent Github Pages Jekyll to run on our website pages
          touch build/web/.nojekyll
          # Make sure minified files are taken into account
          rm build/web/js/.gitignore
          rm build/web/css/.gitignore
          # Workaround needed to avoid failure in deploy (git remote rm origin):
          /usr/bin/git init
          /usr/bin/git remote add origin foo
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@3.6.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/web
